### ISSUE TITLE
Webpack scripts throw an error on Windows

### ISSUE THREAD

**Issue by bcanseco** [rubenspgcavalcante/webpack-chrome-extension-reloader#39] opened 2018-04-13 19:36 UTC
**Type:**
- [x] bug  
- [ ] feature
- [ ] enhancement
- [ ] question
 
**Environment:**
 - OS: Windows 10
 - Version: 1709
 
**Going to open a PR:**
- [x] yes
- [ ] no
 
**Description:**  
```powershell
$ yarn build
yarn build v0.27.5

$ NODE_ENV=production webpack
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

error Command failed with exit code 1.
```

**Comment by rubenspgcavalcante** [comment] 2018-04-20 09:48
Hi @bcanseco , thanks for contributing!
Closing because is a duplicate of #11

**Closed by rubenspgcavalcante** 2018-04-20 09:48 UTC
